###
//Create a new shortened url link in the db
POST http://localhost:4000/api/links
Content-Type: application/json

{
  "code": "google",
  "url": "https://google.com.br"
}

###
//List all data from the db
GET http://localhost:4000/api/links

###
//Get "shortLink", redirect to "originalUrl"
GET http://localhost:4000/rocketseat

###
//Get access metrics
GET http://localhost:4000/api/metrics
